from dataclasses import dataclass

from models.similarity import Similarity


@dataclass
class Evidence:
    """
    Historical evidence generated by the Research Engine.

    This object is descriptive only.
    It never contains recommendations or decisions.
    """

    # Historical sample

    matches: list[Similarity]
    episodes_count: int

    # Return statistics

    average_return_5y: float
    median_return_5y: float
    worst_return_5y: float
    best_return_5y: float

    positive_probability: float

    # Recovery statistics

    average_recovery_months: float | None = None
    median_recovery_months: float | None = None